linux4sam/meta-atmel

- recipes-kernel/linux/linux-yocto-custom_3.10.bb
* fixes "[: =: unexpected operator" error in log.do_deploy when
${UBOOT_FIT_IMAGE} is not set
* already applied in 2f5e00b2456d0e5e7ff0078f1f4de1620b3f1bbb but
then lost while removing bbappends
> linux-yocto-custom_3.10: add missing quotes (re-apply)

- recipes-kernel/linux/linux-yocto-custom_3.10.bb
This is a rework of my previous patch that was reviewed by @alexandrebelloni in #37. This conditionally adds dependencies only when needed and without forcing KERNEL_IMAGETYPE value to "uImage"  
* do_deploy_append() conditionally requires mkimage from u-boot-mkimage-native
when UBOOT_FIT_IMAGE is enabled. mkimage in turn depends on dtc
* use a python anonymous function to conditionally append them to DEPENDS
* fixes errors discussed in [1] when these tools are not installed on the host
machine. Recipes dependencies should be handled by the metadata instead of
relying on host tools.
[1] http://www.at91.com/discussions/viewtopic.php/f,12/t,22461.html
> add missing dependencies when UBOOT_FIT_IMAGE is set

- recipes-graphics/mesa/mesa_%.bbappend
Can be used as fallback opengl implementation since no GPU is present
Check video demos at :
https://dockr.eurogiciel.fr/blogs/embedded/qtwayland-sama5d4-xplained/
Change-Id: I670bd4d7a8ae63664ac19c3e61966db27f1d180f
Signed-off-by: Philippe Coval <philippe.coval@open.eurogiciel.org>
> graphics: mesa gallium package

- recipes-bsp/u-boot/u-boot-at91_git.bb
When backporting the u-boot namespace fix this recipe was missed.
Signed-off-by: Koen Kooi <koen@dominion.thruhere.net>
> u-boot-at91 git: change u-boot include name

- recipes-kernel/linux/atmel-wireless-firmware_git.bb
without it will fail to install and complain with a message like :
/lib/firmware/atmel/wilc1003_firmware.bin [installed-vs-shipped]
Change-Id: I3bb5ef10d4c4229fd15bca57557a7dc5c6c4e204
Signed-off-by: Philippe Coval <rzr@gna.org>
> linux firmware: install all wilc100* firmware files

- conf/machine/sama5d2-xplained-sd.conf
- conf/machine/sama5d2-xplained.conf
- conf/machine/sama5d4-xplained-sd.conf
Hi,
The current commit fixes the dependencies errors with dosfstools-native and mtools-native
on sama5d2-xplained, sama5d2-xplained-sd and sama5d4-xplained-sd machines.
Best regards,
Mylène Josserand
> machine: sama5d2/4-xplained-*: Fix dependencies errors

- conf/machine/sama5d2-xplained-sd.conf
- conf/machine/sama5d2-xplained.conf
- conf/machine/sama5d4-xplained-sd.conf
- qt5-layer/recipes-qt/images/atmel-qt5-demo-image.bb
- recipes-utils/mxt-app/mxt-app/0001-fix-ret-type-in-read_boolean_file.patch
- recipes-utils/mxt-app/mxt-app_git.bb
Hi,
Here is a summary of what these commits handle:
- Fix an error about "qtbase-fonts" package on "atmel-qt5-demo-image"
- Bump mxt-app to version 1.27
- Add a patch on mxt-app to fix gcc6 errors (see PR#53 on upstream project)
- Fix dependencies errors on sama5d2/4-xplained-* machines
Best regards,
Mylène Josserand
> qtbase-fonts, mxt-app and sama5d2/4-xplained-* errors fixed

- conf/machine/at91sam9x5ek-sd.conf
- conf/machine/sama5d2-xplained-sd.conf
- conf/machine/sama5d27-som1-ek-sd.conf
- conf/machine/sama5d3-xplained-sd.conf
- conf/machine/sama5d4-xplained-sd.conf
This fixes the wic image not being updated when the bootloader binaries
would be updated.
Add a dependency to do_deploy of u-boot-at91 to do_image_wic so that the
image is updated when needed.
Signed-off-by: Quentin Schulz <quentin.schulz@free-electrons.com>
> conf: machine: *-sd: add wic dependency on do_deploy of u-boot-at91

- recipes-kernel/linux/linux-at91_4.9.bb
Same change as commit 54d1a28, applied to the 4.9 kernel recipe.
> linux-at91_4.9: Fix RDEPENDS key replacement

- scripts/nandflash.tcl
Hi,
This commit fixes u-boot environment address and mtdparts in nandflash.tcl script to match the configs of sam9 and sama5 in u-boot-at91.
Previously, the script uses old address for u-boot environment (0x000C0000) that has now been moved to 0x00140000 since commit [4744f870b23d7f84d13aa767835b3a457e34e181](https://github.com/linux4sam/u-boot-at91/commit/4744f870b23d7f84d13aa767835b3a457e34e181). As u-boot-env is not initialized, u-boot is detecting a CRC error and is using its default values (related to jffs2). As it doesn't match generated image, boot sequence is interrupted.
I was only able to test it on at91sam9g45ekes board and it is properly booting.
Regards
> Fix u-boot environment address and mtdparts in nandflash.tcl script

- conf/distro/poky-atmel.conf
Hello,
Here is a commit to fix the issue on sumo's branch about update-alternatives of klogd.
The warning shown was:
WARNING: atmel-xplained-demo-image-1.0-r1 do_rootfs: busybox.postinst
returned 1, marking as unpacked only, configuration required on target.
WARNING: atmel-xplained-demo-image-1.0-r1 do_rootfs: Intentionally
failing postinstall scriptlets of ['busybox'] to defer them to first
boot is deprecated. Please place them into pkg_postinst_ontarget_${PN} ().
If deferring to first boot wasn't the intent, then scriptlet failure may
mean an issue in the recipe, or a regression elsewhere.
Details of the failure are in /home/mylene/yocto/build_atmel/tmp/work/\
sama5d4_xplained_sd-poky-linux-gnueabi/atmel-xplained-demo-image/1.0-r1/temp/log.do_rootfs.
See the commit log for more details …
> distro: Fix syslog update-alternatives issue

- recipes-bsp/u-boot/u-boot-atmel.inc
Without this option, the following
error appears (when integrating Mender for instance) :
=> ERROR: Nothing PROVIDES "u-boot"
Signed-off-by: Pierre-Jean Texier <pierre-jean.texier@lafon.fr>
> u-boot-at91: add u-boot to PROVIDES

- dynamic-layers/qt5-layer/recipes-qt/qt5/qtbase_%.bbappend
* use proper overrides and apply extra patches and PACKAGECONFIGs only
for sama5 and at91sam9
* drop kms PACKAGECONFIG, almost the same is in qtbase with correct
dependencies:
PACKAGECONFIG[kms] = "-kms,-no-kms,drm virtual/egl"
Signed-off-by: Martin Jansa <Martin.Jansa@gmail.com>
> qtbase: stop modifying it for other MACHINEs

- conf/machine/include/sama5.inc
This avoids mount warnings e.g. when it tries to mount
/dev/mmcblkp1 onto /boot and such a partition is non-existent
and boot falls into emergency shell.
=> Mounting all non-network filesystems...
mount: mounting /dev/mmcblkp1 on /boot failed: No such file or directory
Cannot continue due to errors above, starting emergency shell.
(cherry picked from commit dcd00e2883f6404bdc9c22b01c31a13c4f1495e0)
> [thud] : cherry-pick (sama5.inc: Add wic option to not update fstab)

- recipes-atmel/apps/atmel-qt-demo-init_1.1.bb
OE-Core has reworded the license file see
https://git.openembedded.org/openembedded-core/commit/?id=f8c9c511b5f1b7dbd45b77f345cb6c048ae6763e
> atmel-qt-demo-init: Update checksums for LICENSE

- recipes-bsp/u-boot/u-boot-envs-atmel.inc
This commit fixes :
| ERROR: _exec_cmd: ...
| output: install: cannot stat '<path>/tmp/deploy/images/sama5d27-som1-ek-sd/uboot.env': No such file or directory
Also fixes the deploy step. Now, the wic image contains the file uboot.env:
$ wic ls <path>/tmp/deploy/images/sama5d27-som1-ek-sd/<image>.rootfs.wic:1
Volume in drive : is boot
Volume Serial Number is 0F36-08EB
Directory for ::/
AT91-S~1 DTB     44915 2019-05-13   7:03  at91-sama5d27_som1_ek.dtb
BOOT     BIN     19177 2019-05-13   7:03
SAMA5D~1 ITB   4089100 2019-05-13   7:03  sama5d27_som1_ek.itb
u-boot   bin    463975 2019-05-13   7:03
uboot    env     16384 2019-05-13   7:03
ZIMAGE         4023792 2019-05-13   7:03  zImage
> bsp/u-boot: fix default environment generation

- recipes-bsp/at91bootstrap/at91bootstrap_3.8.12.bb
- recipes-bsp/at91bootstrap/at91bootstrap_git.bb
As reported by Pierre-Jean, meta-atmel breaks BB_NO_NETWORK.
Instead, only break at91bootstrap_git at build time as it would not build anyway. Maybe the other solution would be to drop the recipe as it has DEFAULT_PREFERENCE = "-1" and probably doesn't see much testing.
> Fix at91bootstrap

- recipes-bsp/at91bootstrap/at91bootstrap-sam-ba_3.8.12.bb
Due to the fact this recipe (at91bootstrap-sam-ba) requires the
at91bootstrap_${PV} recipe, the code source location ($S) gets confused, and
bitbake doesn't know where to find the sources. Therefore it can't patch, do
the licensing, etc.
By explicitly setting the $S variable, bitbake is able to find the sources.
Signed-off-by: Trevor Woerner <twoerner@gmail.com>
> at91bootstrap-sam-ba: fix S

- recipes-bsp/at91bootstrap/at91bootstrap_3.8.13.bb
at91bootstrap is the in-house proprietary bootloader.
We should not apply patches to it via meta yocto layer.
all patches should go through at91bootstrap project and at91bootstrap
maintainers.
The patches here are for reference only, and should not be applied
in the recipes.
Patch owners should send patches through at91bootstrap patch channels.
Signed-off-by: Eugen Hristev <eugen.hristev@microchip.com>
> at91bootstrap: remove stray patch from recipe

- recipes-bsp/at91bootstrap/at91bootstrap_3.9.0.bb
This includes the following changes:
98145e6 Makefile: prepare 3.9.0-rc2
409fb89 lib: memcpy: fix memcpy and memset to standard return pointers
cae6f80 board: sama5d2: fix plla charge pump register
ce0d89d include: arch: pmc-v1: fix macros values
d15b9de driver: pmc: pll-clk: remove unnecessary #ifdef
bee0d23 driver: pmc: pll-clk: revert to using *ALT_MULA* macros
> at91bootstrap: bump to tag v3.9.0-rc2

- recipes-bsp/at91bootstrap/at91bootstrap_3.9.0.bb
This includes the following changes:
13ef0f7 Makefile: prepare 3.9.0-rc4
0d61b6d board: sama5d27_wlsom1_ek: add config for BSR
83e11c5 driver: ddramc: add bsr support for lpddr2 memories with sama5d2
a5cbe08 board: sam9x60ek: wilc power sequence
817a7d8 sama5d27_som1_ek: fix over-consumption erratum check
016e638 board: sama5d27_wlsom1_ek: fix QSPI mode
7a2d6ba board: sam9x60_sdr_sip_eb: fix MPDDR bit selected by error
> at91bootstrap: bump to tag v3.9.0-rc4

- conf/layer.conf
- recipes-atmel/apps/atmel-qt-demo-init_1.1.bb
Turn dep in fbset into rdep, its only needed during runtime in atmel-qt-demo-init
fbset has machine specific configuration but the ABI is safe as far as
atmel-qt-demo-init is concerned, this ensures that atmel-qt-demo-init is
not recompiling for no reason when machine is changed e.g. form qemuarm
to qemuarm64
Fixes
atmel-qt-demo-init-1.1: Package version for package atmel-qt-demo-init-src went backwards which would break package feeds from (0:1.1-r2.17 to 0:1.1-r2.16) [version-going-backwards]
atmel-qt-demo-init-1.1: Package version for package atmel-qt-demo-init-dbg went backwards which would break package feeds from (0:1.1-r2.17 to 0:1.1-r2.16) [version-going-backwards]
atmel-qt-demo-init-1.1: Package version for package atmel-qt-demo-init-staticdev went backwards which would break …
> layer.conf: Whitelist fbset->atmel-qt-demo-init dependency

- recipes-bsp/at91bootstrap/at91bootstrap_3.9.0.bb
This includes the following changes:
7b42a8e Makefile: prepare 3.9.0-rc5
69e8f73 sam9x60: adapt PMC_PLL_ACR to datasheet
> at91bootstrap: bump to tag v3.9.0-rc5

- dynamic-layers/qt5-layer/recipes-qt/apps/homeautomation_1.10.bb
- dynamic-layers/qt5-layer/recipes-qt/apps/minehunt_1.7.bb
- dynamic-layers/qt5-layer/recipes-qt/apps/qmlbrowser_1.7.bb
- dynamic-layers/qt5-layer/recipes-qt/apps/samegame_1.6.bb
- dynamic-layers/qt5-layer/recipes-qt/apps/smartrefrigerator_1.6.bb
- recipes-bsp/at91bootstrap/at91bootstrap_3.8.12.bb
Pointing archives can lead to checksums issues due to github
regeneration.The protocol https is preconised to avoid proxy issues.
See https://github.com/linux4sam/meta-atmel/pull/99 for details.
Signed-off-by: Kamel Bouhara <kamel.bouhara@bootlin.com>
> Rework recipes to fetch using git and https protocol

- recipes-egt/apps/egt-benchmark/0001-configure-Do-not-add-C-compiler-flags-to-CPPFLAGS.patch
- recipes-egt/apps/egt-benchmark_1.0.bb
This ensures that configure tests using g++ do not fail
Fixes errors like
checking for pthread-config... no
configure: error: Can not find pthreads.  This is required.
> egt-benchmark: Do not use c++ flags in CPPFLAGS

- recipes-bsp/at91bootstrap/at91bootstrap_3.9.3.bb
Branch "at91bootstrap-3.x-python3" does not exists anymore since
master includes python3 support, so use master instead.
Fixes:
- http://51.75.135.20:8080/job/sama5d27-som1-ek-sd/75/console
> at91bootstrap: do not use specific branch

- recipes-support/python-cryptoauthlib/python3-cryptoauthlib_20200208.bb
Added udev and also 'CRYPTOAUTHLIB_NOUSB = True' If a USB kit is not being used then environment variable CRYPTOAUTHLIB_NOUSB  needs to be set for the python build.
> added udev & CRYPTOAUTHLIB_NOUSB = True

- recipes-security/cryptoauthlib/cryptoauthlib_git.bb
gcc10 has changed the defaults to use -fno-common and this library needs
some work to get it going with -fno-common, until thats fixed lets keep
using good old -fcommon
Fixes a lot of multiple definition of XXX errors
> cryptoauthlib: Use -fcommon to compile it

- recipes-egt/apps/noto-fonts.bb
cp does not maintain proper user name and group, therefore use install
utility to install files.
Use datadir instead of hardcoding /usr/share
Mark do_compile as noexec since we only need do_install onwards
> noto-fonts: Use installed file permissions

- conf/layer.conf
This ensures that this package can stay allarch and does not recompile
when machine is changed
Fixes
=== Comparing signatures for task do_package_write_ipk.sigdata between qemux86copy and qemuarm ===
ERROR: noto-fonts different signature for task do_package_write_ipk.sigdata between qemux86copy and qemuarm
> layer.conf: Add noto-fonts dep on fontconfig to exclude from signatures

- recipes-graphics/libegt/libegt_1.1.bb
Fixes
| ./detail/erawimage.h:39:1: error: static_assert failed due to requirement 'end
ian::native == endian::little' "eraw implementation only works on little"
| static_assert(endian::native == endian::little,
| ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| 1 error generated.
| make[3]: *** [Makefile:2532: detail/libegt_la-eraw.lo] Error 1
> libegt: Skip it for Big-endian targets

- recipes-bsp/u-boot/files/envs/sam9x60ek.txt
For the sam9x60ek board in NAND configuration (not SD) the current value `ubi.mtd=5` seem to be wrong, being the correct `ubi.mtd=11` for the current kernel+board default configuration with flashing on NAND.
This can be seen in detail from the following:
```
Linux version 5.4.41-linux4sam-2020.04 (oe-user@oe-host) (gcc version 9.3.0 (GCC)) #1 Mon May 25 16:58:23 UTC 2020
CPU: ARM926EJ-S [41069265] revision 5 (ARMv5TEJ), cr=0005317f
CPU: VIVT data cache, VIVT instruction cache
OF: fdt: Machine model: Microchip SAM9X60-EK
...
spi-nor spi0.0: sst26vf064b (8192 Kbytes)
6 fixed-partitions partitions found on MTD device spi0
Creating 6 MTD partitions on "spi0":
0x000000000000-0x000000040000 : "qspi: at91bootstrap"
0x000000040000-0x000000100000 : "qspi: bootloader"
0x000000100000-0x000000140000 …
```
> u-boot: fix ubi partition for default environment for sam9x60ek board

- recipes-devtools/sam-ba/sam-ba_3.3.1.bb
Upgrades current sam-ba flashing tool from 3.2.3 to 3.3.1. The newer (well Dec 2019) version, among other fixes, supports the sam9x60 device (and sam9x60-ek board) which we already have in meta-atmel as a machine (see [sam9x60ek.conf](https://github.com/linux4sam/meta-atmel/blob/dunfell/conf/machine/sam9x60ek.conf)) but we otherwise not have a sam-ba which actually supports its flashing.
Signed-off-by: Federico Pellegrin fede@evolware.org
> sam-ba: upgrade to 3.3.1

- recipes-atmel/images/microchip-graphics-image.bb
- recipes-egt/apps/egt-benchmark_1.0.bb
- recipes-egt/apps/egt-launcher_1.1.bb
- recipes-egt/apps/egt-media_1.3.bb
- recipes-egt/apps/egt-samples_1.1.bb
- recipes-egt/apps/egt-thermostat_1.1.bb
Since libegt will only work on Little-endian targets, until its fixed
these recipes should also be built form LE only targets
> recipes/images: Cordon off libegt dependent packages

- recipes-core/udev-at91/udev-rules-at91.bb
The licenses were renamed to match their SPDX names, fix the
references in LIC_FILES_CHKSUM.
> udev-rules-at91: Update common-licenses references to match new names

- recipes-egt/apps/egt-media_1.3.bb
It depends on ffmpeg which has implications on commercial use
check if user has checked it and enabled it
> egt-media: Check for license befor including gstreamer1.0-libav

- recipes-graphics/libegt/libegt_1.1.bb
To use latest gcc/clang etc we need fixes like
https://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=commit;h=9e917efe603b0d756f258cad6eb2056559284ed0
Since the tests in these m4 needs updated code snippets the older
snippets are flagged as warnings/errors during test compile, resulting
in configure tests resulting in failures
> libegt: Search OE aclocal before local m4 files

- recipes-kernel/linux/mchp-wireless-firmware_15.6.bb
Specify branch parameter in SRC_URI since its now needed to be
explicitly mentioned
> mchp-wireless-firmware: Upgrade to 15.6 release

- recipes-egt/apps/egt-launcher_1.2.bb
- recipes-egt/apps/files/0001-launcher-Switch-to-using-std-filesystem.patch
- recipes-graphics/libegt/libegt/0001-Use-std-filesystem-instead-of-std-experimental-files.patch
- recipes-graphics/libegt/libegt_1.6.bb
@noglitch support for std::filesystem is still needed to get the latest libegt working. using c++17 is fixed in this version which is great but code for experimental::filesystem also needs to change
> Fix libegt/egt-launcher with clang/libc++

- conf/machine/include/sama7.inc
- conf/machine/sama7g5ek-emmc.conf
- conf/machine/sama7g5ek-sd.conf
- recipes-kernel/linux/linux-at91_5.4.81.bb
KBUILD_DEFCONFIG is confusing people, stop using it and simplify recipes
Signed-off-by: Alexandre Belloni <alexandre.belloni@bootlin.com>
> kernel: Drop KBUILD_DEFCONFIG

- recipes-bsp/dt-overlay-mchp/dt-overlay-mchp_git.bb
- recipes-bsp/u-boot/u-boot-envs-atmel.inc
The logging class that provides the standard shell functions used to log messages, that should be use in tasks (i.e. bbplain, bbnote, bbwarn, bberror, bbfatal, and bbdebug).
> Use bbnote instead echo in tasks

- recipes-multimedia/gstreamer1.0-plugins/gstreamer1.0-plugins-hantro.inc
Use of git submodules [no longer work in Kirkstone](https://lists.yoctoproject.org/g/yocto/message/59818), this PR fixes the recipe.
> Fix broken recipe for gstreamer1.0 plugins hantro

- recipes-support/p11-kit/p11-kit_0.24.1.bbappend
The master meta-atmel cannot be built against master Yocto as the p11-kit was upgraded to 0.25.0.
There is no need to upgrade this bbappend as the upstream recipe already includes the required BBCLASSEXTEND, so we can simply delete the bbappend without any harm.
http://cgit.openembedded.org/openembedded-core/tree/meta/recipes-support/p11-kit/p11-kit_0.25.0.bb
> p11-kit: delete unnecessary bbappend

- recipes-security/cryptoauthlib/cryptoauthlib_git.bb
ERROR: cryptoauthlib-1.0+git-r0 do_fetch: Fetcher failure: Repository https://github.com/MicrochipTech/cryptoauthlib.git has LFS content, install git-lfs on host to download (or set lfs=0 to ignore it)
> cryptoauthlib: add lfs=0 to SRC_URI to avoid git errors in do_unpack
